# configs/ensemble_configs/ensemble_config.yaml
data_module: "src.data.datamodules.sketch_datamodule.SketchDataModule" # custom data module path

# configs for data module
data_config_path: "configs/data_configs/sketch_config.yaml"
augmentation_config_path: "configs/augmentation_configs/sketch_augmentation.yaml"

name: "" 

model_EVA: # eva clip model
  model:
    model_name: "eva02_large_patch14_448.mim_m38m_ft_in22k_in1k"  # model name
    num_classes: 500
    pretrained: True
  module: "src.plmodules.sketch_module.SketchModelModule"
  checkpoint: "/data/ephemeral/home/level1-imageclassification-cv-02/Sketch/minsol/eva.ckpt"

model_CNN: # convnext model
  model:
    model_name: "convnext_large_mlp.clip_laion2b_augreg_ft_in1k"  # model name
    num_classes: 500
    pretrained: True
  module: "src.plmodules.sketch_CNN_module.SketchModelModule_CNN"
  checkpoint: "/data/ephemeral/home/level1-imageclassification-cv-02/Sketch/wxm28lf3/checkpoints/epoch=7-step=3008.ckpt"

trainer:
  accelerator: gpu
  devices: 1
  default_root_dir: "output" # 

seed: 42

logging:
  log_level: "INFO"
  log_file: "logs/ensemble.log"