# 여기 본인 모듈에 맞게 경로 고쳐야 합니다. 

# Data를 처리하기 위한 custom data module의 경로
# Dataset 과 Dataloader 를 포함하는 개념. 
data_module: "src.data.custom_datamodules.sketch_datamodule.SketchDataModule"

# 데이터 관련 설정을 포함하는 YAML 파일의 경로
# 훈련/검증/테스트 세트 분할비율, 배치크기, 데이터로딩방식 등등.  
data_config_path: "configs/data_configs/sketch_config.yaml"
augmentation_config_path: "configs/augmentation_configs/sketch_augmentation.yaml"

# 모델들의 모듈과 각각의 체크포인트 경로 설정 -> 이는 앙상블 모델을 구성하는데 사용가능
models:
  - module: "/data/ephemeral/home/level1-imageclassification-cv-02/src/plmodules/sketch_module.py"
    checkpoint: "/data/ephemeral/home/level1-imageclassification-cv-02/Sketch/mflnadc3/checkpoints/epoch=19-step=7520.ckpt"
  - module: "/data/ephemeral/home/level1-imageclassification-cv-02/src/plmodules/sketch_CNN_module.py"
    checkpoint: "/data/ephemeral/home/level1-imageclassification-cv-02/Sketch/ieif5wb5/checkpoints/epoch=16-step=6392.ckpt"

#개별모델에 대한 설정을 정의
model:
  name: "ensemble_eva02_convnext"
  num_classes: 500
  pretrained: True

trainer:
  accelerator: gpu
  devices: 1

seed: 42  # 시드 값 추가
