# configs/data_configs/sketch_config.yaml
data:
  name: Sketch
  raw_data_path: data/train
  test_data_path: data/test
  processed_data_path: data/processed/Sketch
  train_df_path: data/train.csv
  test_df_path: data/test.csv
  train_val_split: 0.8
  val_test_split: 0.7
  batch_size: 32
  num_workers: 8
  pin_memory: true
