data_module: "src.data.custom_datamodules.sketch_datamodule.SketchDataModule"
model_module: "src.plmodules.sketch_module.SketchModelModule"

data_config_path: "configs/data_configs/sketch_config.yaml"
augmentation_config_path: "configs/augmentation_configs/sketch_augmentation.yaml"

sweep_path: "configs/train_configs/train/sweep.yaml"
use_sweep: False #sweep 사용시 True 로.(default 는 False)

model:
  model_name: "eva02_large_patch14_448.mim_m38m_ft_in22k_in1k"
  num_classes: 500
  pretrained: True

optimizer:
  name: Adam
  params:
    lr: 2e-4

scheduler:
  name: StepLR
  params:
    step_size: 1
    gamma: 0.7

trainer:
  max_epochs: 5
  accelerator: gpu
  devices: 4 
  default_root_dir: "output" #output 폴더에 추가.
  strategy : "ddp" 

callbacks:
  model_checkpoint:
    monitor: val_acc
    save_top_k: 3
    mode: max
  early_stopping:
    monitor: val_acc
    patience: 3
    mode: max

wandb_name: "eva02(mim)-randaug-onlyheaddrop-6nonfreeze-20epochs"


#GradCAM 설정 추가
visualize_gradcam : True
gradcam:
  target_layer : model.model.blocks.23.mlp.act #모델의 마지막 어턴션 (본인 모델의 CAM 을 보고 싶다면 마지막 레이어를 적어주면됨.)
  image_index : 0
  save_dir : "/home/jaegun/Study_jaegun/AI_tech/Team_project/9월 팀프로젝트/level1-imageclassification-cv-02/output/GradCam/gradcam_result.png"
  model_name : "eva02_large_patch14_448"
seed: 42  # 시드 값 추가
