data_module: "src.data.datamodules.sketch_datamodule.SketchDataModule" # data module path
model_module: "src.plmodules.sketch_module.SketchModelModule" # pl module path

data_config_path: "configs/data_configs/sketch_config.yaml" # dataset config path
augmentation_config_path: "configs/augmentation_configs/sketch_augmentation.yaml" # augmentation config path

sweep_path: "configs/train_configs/train/sweep.yaml" # sweep config path
use_sweep: True # for hyperparameter sweep

model:
  model_name: "eva02_large_patch14_448.mim_m38m_ft_in22k_in1k"
  num_classes: 500
  pretrained: True

optimizer:
  name: Adam
  params:
    lr: 2e-4

scheduler:
  name: StepLR
  params:
    step_size: 1
    gamma: 0.7

trainer:
  max_epochs: 1
  accelerator: gpu
  devices: 4 
  default_root_dir: "output"
  strategy : "ddp" 

callbacks:
  model_checkpoint:
    monitor: val_acc
    save_top_k: 
    mode: max
  early_stopping:
    monitor: val_acc
    patience: 10
    mode: max

wandb_name: "eva02(mim)-randaug-onlyheaddrop-6nonfreeze-20epochs"

# Attention 시각화 설정 추가
visualize_attention: False
attention:
  input_image_dir: "data/train"
  output_image_dir: "output/Transformer"
  layer_index: 23
  head_index: 7