data_module: "src.data.custom_datamodules.sketch_datamodule.SketchDataModule"
model_module: "src.plmodules.sketch_module.SketchModelModule"

data_config_path: "configs/data_configs/sketch_config.yaml"
augmentation_config_path: "configs/augmentation_configs/sketch_augmentation.yaml"

sweep_path: "configs/train_configs/train/sweep.yaml"
use_sweep: False #sweep 사용시 True 로.(default 는 False)

model:
  model_name: "eva02_large_patch14_448.mim_m38m_ft_in22k_in1k"
  num_classes: 500
  pretrained: True

optimizer:
  name: Adam
  params:
    lr: 2e-4

scheduler:
  name: StepLR
  params:
    step_size: 1
    gamma: 0.7

trainer:
  max_epochs: 20
  accelerator: gpu
  devices: 1 
  default_root_dir: "output" #output 폴더에 추가.
  # strategy : "ddp" 

callbacks:
  model_checkpoint:
    monitor: val_acc
    save_top_k: 3
    mode: max
  early_stopping:
    monitor: val_acc
    patience: 3
    mode: max

wandb_name: "eva02(mim)-randaug-onlyheaddrop-6nonfreeze-20epochs"

seed: 42  # 시드 값 추가
