data_module: "src.data.custom_datamodules.sketch_datamodule.SketchDataModule"
model_module: "src.plmodules.sketch_module.SketchModelModule"

data_config_path: "configs/data_configs/sketch_config.yaml"
augmentation_config_path: "configs/augmentation_configs/sketch_augmentation.yaml"

model:
  model_name: "resnet18"
  num_classes: 500
  pretrained: True
  # lr: 0.001

optimizer:
  name: Adam
  params:
    lr: 0.001

scheduler:
  name: StepLR
  params:
    step_size: 1
    gamma: 0.7

trainer:
  max_epochs: 50
  accelerator: gpu
  devices: 1

callbacks:
  model_checkpoint:
    monitor: val_loss
    save_top_k: 3
    mode: min
  early_stopping:
    monitor: val_loss
    patience: 5
    mode: min

seed: 42  # 시드 값 추가
