program: train.py
method: 'bayes'  # Hyperparameter search strategy
command:
  - competition1/bin/python  # Python 실행 경로
  - ${program}  # train.py 실행
  - --config=configs/train_configs/train/config.yaml  # config 파일 경로
  - --use_wandb

metric:
  name: 'val_acc'  # Metric to optimize
  goal: 'maximize'

parameters:
  learning_rate:
    distribution: 'uniform'
    min: 1e-6
    max: 1e-3
  lr_scheduler:
    values: ['StepLR']
  step_size:
    values: [1]
    # distribution: 'int_uniform'
    # min: 1
    # max: 1
  gamma:
    values: [0.5, 0.7]
    # distribution: 'uniform'
    # min: 0.45
    # max: 0.8
  num_ops:
    values: [2, 3, 4]
  magnitude:
    values: [9, 11, 13]
  drop_head_prob:
    distribution: 'uniform'
    min: 0.3
    max: 0.5
  drop_path_prob:
    distribution: 'uniform'
    min: 0.1
    max: 0.5
  attn_drop_prob:
    distribution: 'uniform'
    min: 0.1
    max: 0.3
