


program: train.py
method: 'bayes'  # Hyperparameter search strategy
command:
  - competition1/bin/python  # Python 실행 경로
  - ${program}  # train.py 실행
  - --config=configs/train_configs/train/config.yaml  # config 파일 경로
  - --use_wandb

metric:
  name: 'val_acc'  # Metric to optimize
  goal: 'maximize'

parameters:
  learning_rate:
    distribution: 'uniform'
    min: 1e-6
    max: 1e-4
  lr_scheduler:
    values: ['StepLR']
  step_size:
    distribution: 'int_uniform'
    min: 1
    max: 3
  gamma:
    distribution: 'uniform'
    min: 0.5
    max: 0.8
  num_ops:
    values: [2, 3]
  magnitude:
    values: [7, 9, 11]
  drop_path_prop:
    distribution: 'uniform'
    min: 0.1
    max: 0.5
  attn_drop_prob:
    distribution: 'uniform'
    min: 0.1
    max: 0.3
